Code/BudgetWebsite/BudgetWebsite/Models/ChartViewModel.cs
using System.Collections.Generic;
using Chart.Mvc.ComplexChart;
using Chart.Mvc.SimpleChart;
using Services.Enum;

namespace Databank.Models
{
    public class ChartViewModel
    {
        public ChartViewModel()
        {
            CanvasWidth = "300";
            CanvasHeight = "300";
        }

        public string ChartName { get; set; }

        public string CanvasId { get; set; }

        public BarChart BarChart { get; set; }

        public PieChart PieChart { get; set; }

        public IEnumerable<ComplexDataset> ChartDataset { get; set; }

        public IEnumerable<SimpleData> SimpleChartDataset { get; set; }

        public IEnumerable<string> Labels { get; set; }

        public ChartType ChartType { get; set; }

        public string CanvasWidth { get; set; }

        public string CanvasHeight { get; set; }
    }
}

Code/BudgetWebsite/BudgetWebsite/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using Databank.Extensions;
using Databank.Helpers;
using Microsoft.AspNet.Identity;
using PagedList;
using Services.Enum;
using Services.Models;
using Databank.Models;
using Ionic.Zip;
using Services.Services;

namespace Databank.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private readonly AccountService _accountService;
        private readonly AdminService _adminService;
        private readonly int _currentUserId;

        public AdminController()
        {
            _accountService = new AccountService();
            _adminService = new AdminService();
            _currentUserId = Convert.ToInt32(System.Web.HttpContext.Current.User.Identity.GetUserId());
        }

        public ActionResult Index()
        {
            if (!SecurityHelper.IsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        public ActionResult Register()
        {
            if (!SecurityHelper.IsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            var registerViewModel = new RegisterViewModel { PermissionList = BuildPermissionList() };
            return View(registerViewModel);
        }

        public ActionResult Users(int? page, string currentFilter, string searchString)
        {
            if (!SecurityHelper.IsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            return GetUserListViewModel(page, currentFilter, searchString);
        }

        public ActionResult RelevantAuthorities(int? page, string currentFilter, string searchString)
        {
            if (!SecurityHelper.IsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            return GetRelevantAuthoritiesViewModel(page, currentFilter, searchString);
        }

        public ActionResult RelevantAuthority(int relevantAuthorityId)
        {
            if (!SecurityHelper.IsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            var raVm = new RelevantAuthorityViewModel();
            var ra = _adminService.GetRelevantAuthorityById(relevantAuthorityId);

            raVm.RelevantAuthorityId = ra.RelevantAuthorityId;
            raVm.SelectedDepartment = ra.Department.DepartmentId;
            raVm.ContactDetails = ra.ContactDetails;
            raVm.RelevantAuthorityName = ra.RelevantAuthorityName;
            raVm.DepartmentList = GetAllDepartments();

            return View(raVm);
        }

        private List<SelectListItem> GetAllDepartments()
        {
            var depts = _adminService.GetAllDepartments();
            var deptlist = depts.Select(dept => new SelectListItem
            {
                Text = dept.DepartmentName.ToString(),
                Value = dept.DepartmentId.ToString()
            })
                .ToList();

            return deptlist;
        }

        [HttpPost]
        public ActionResult RelevantAuthority(RelevantAuthorityViewModel raVm)
        {
            if (!ModelState.IsValid)
            {
                raVm.DepartmentList = GetAllDepartments();
                return View(raVm);
            }

            if (!SecurityHelper.IsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            var relevantAuthority = new RelevantAuthority
            {
                RelevantAuthorityId = raVm.RelevantAuthorityId,
                Department = new Department { DepartmentId = raVm.SelectedDepartment },
                ContactDetails = raVm.ContactDetails,
                RelevantAuthorityName = raVm.RelevantAuthorityName
            };

            _adminService.UpdateRelevantAuthorityId(relevantAuthority);

            raVm.DepartmentList = GetAllDepartments();
            ViewBag.ShowSuccess = "true";
            ViewBag.SuccessMessage = $"{raVm.RelevantAuthorityName} - updated successfully";

            return View(raVm);
        }

        public ActionResult Export()
        {
            var exportViewModel = new ExportViewModel
            {
                StageList = BuildStageList(),
                StageYearList = BuildStageYearList()
            };

            return View(exportViewModel);
        }

        public ActionResult ExportHistory()
        {
            var exportListViewModel = new ExportListViewModel
            {
                Exports = _adminService.GetAllExports()
            };

            return View(exportListViewModel);
        }

        public ActionResult Templates(int exportId)
        {
            var templates = _adminService.GetTemplatesByExportId(exportId);
            return View(templates);
        }

        public ActionResult DownloadAllTemplates()
        {
            using (var zip = new ZipFile())
            {
                var filePath = ConfigurationManager.AppSettings["DownloadTemplateFilePath"];
                zip.AddDirectory(filePath);

                var output = new MemoryStream();
                zip.Save(output);
                return File(output.ToArray(), "application/zip", "Templates.zip");
            }
        }

        public ActionResult Year()
        {
            var yearViewModel = new YearViewModel { YearList = _adminService.GetAllYears() };
            return View(yearViewModel);
        }

        [HttpPost]
        public ActionResult Year(YearViewModel yearViewModel)
        {
            ViewBag.ShowSuccess = "false";
            var newYear = yearViewModel.NewYear ?? 0;

            var yearList = _adminService.GetAllYears();
            yearViewModel.YearList = yearList;

            if (!ModelState.IsValid)
            {
                return View(yearViewModel);
            }

            var allYears = yearList.Select(x => x.Item1).ToList();

            if (allYears.Contains(newYear))
            {
                foreach (var modelStateValue in ModelState.Values)
                {
                    modelStateValue.Errors.Clear();
                }

                ModelState.AddModelError("", $"{newYear} already exists - it cannot be added twice");
                return View(yearViewModel);
            }

            _adminService.AddYear(newYear, _currentUserId);
            yearViewModel.YearList = _adminService.GetAllYears();

            ViewBag.ShowSuccess = "true";
            ViewBag.SuccessMessage = $"{yearViewModel.NewYear} - created successfully";

            return View(yearViewModel);
        }

        [HttpPost]
        public ActionResult Export(ExportViewModel exportViewModel)
        {
            exportViewModel.StageList = BuildStageList();
            exportViewModel.StageYearList = BuildStageYearList();

            if (!ModelState.IsValid)
            {
                return View(exportViewModel);
            }

            _adminService.QueueTemplateExport(exportViewModel.SelectedStage, exportViewModel.SelectedStageYear, _currentUserId);

            ViewBag.ShowSuccess = "true";
            ViewBag.SuccessMessage = "Templates will be available for circulation within twenty minutes";

            return View(exportViewModel);
        }

        [HttpPost]
        public ActionResult Register(RegisterViewModel registerViewModel)
        {
            ViewBag.ShowSuccess = "false";
            if (!ModelState.IsValid)
            {
                registerViewModel.PermissionList = BuildPermissionList();
                return View(registerViewModel);
            }

            var result = _accountService.RegisterUser(registerViewModel.Email, registerViewModel.Password, registerViewModel.FirstName, registerViewModel.LastName, registerViewModel.SelectedPermission);

            if (result.Success)
            {
                ViewBag.ShowSuccess = "true";
                ViewBag.SuccessMessage = $"{registerViewModel.Email} - created successfully";

                registerViewModel.PermissionList = BuildPermissionList();
                return View(registerViewModel);
            }

            foreach (var modelStateValue in ModelState.Values)
            {
                modelStateValue.Errors.Clear();
            }

            ModelState.AddModelError("", result.Message);

            registerViewModel.PermissionList = BuildPermissionList();
            return View(registerViewModel);
        }

        public ActionResult DeleteUser(int userId)
        {
            if (SecurityHelper.IsAdmin())
            {
                _adminService.DeleteUser(userId);
            }

            return RedirectToAction("Users");
        }

        private ActionResult GetRelevantAuthoritiesViewModel(int? page, string currentFilter, string searchString)
        {
            var pageSize = ConfigurationManager.AppSettings["PageSize"] != null ? Convert.ToInt32(ConfigurationManager.AppSettings["PageSize"]) : 20;

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var raList = _adminService.GetRelevantAuthorityList(page ?? 1, pageSize, searchString);

            var pagenumber = (page ?? 1) - 1;
            var totalCount = raList.TotalCount;

            var pagedRas = new StaticPagedList<RelevantAuthority>(raList.RelevantAuthorities, pagenumber + 1, pageSize, totalCount);
            return View("RelevantAuthorities", pagedRas);
        }

        private List<SelectListItem> BuildPermissionList()
        {
            var role = _accountService.GetUserRole(_currentUserId);
            var list = new List<SelectListItem>();

            if (role == Role.Administrator)
            {

Code/BudgetWebsite/BudgetWebsite/Controllers/ContactUsController.cs
using System.Web.Mvc;

namespace Databank.Controllers
{
    public class ContactUsController : Controller
    {
        // GET: ContactUs
        public ActionResult Index()
        {
            return View();
        }
    }
}

Code/BudgetWebsite/BudgetWebsite/Controllers/MenuController.cs
using System.Web.Mvc;

namespace Databank.Controllers
{
    public class MenuController : Controller
    {
        public ActionResult RenderMenu()
        {
            return View("_Menu");
        }
    }
}

Code/BudgetWebsite/BudgetWebsite/Views/Shared/_Chart.cshtml
@using Chart.Mvc.Extensions
@using Services.Enum
@model Databank.Models.ChartViewModel


@{
    string canvas = Model.CanvasId;
    string legendName = Model.CanvasId + "_legend";
}


<h3>@Model.ChartName</h3>
<div class="clearboth"></div>
<div class="chart-canvas">
    <canvas id="@canvas" width="@Model.CanvasWidth" height="@Model.CanvasHeight"></canvas>

    @if (Model.ChartType == ChartType.PieChart)
    {
        @Html.CreateChart(canvas, Model.PieChart)
    }
    else if (Model.ChartType == ChartType.BarChart)
    {
        @Html.CreateChart(canvas, Model.BarChart)
    }
</div>
<div id="@legendName" class="chart-legend"></div>

<div class="clearboth"></div>

Code/BudgetWebsite/BudgetWebsite/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @{
        var title = ViewBag == null || ViewBag.Title == null ? string.Empty : ViewBag.Title;
    }

    <title>@string.Format("Budget - Receipts and Expenditure Management - {0}", title)</title>
    @Scripts.Render("~/bundles/custom")
    @Styles.Render("~/Content/bundlecss")
    @Styles.Render("~/Content/bundlespscss")
</head>
<body>
    <div class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        @Html.ActionLink("Contact Us", "Index", "ContactUs", null, new { @class = "nav-link" })
                    </li>
                </ul>
                @if (Request.IsAuthenticated)
                {
                    <div class="user-area">
                        <i class="icon-user icons header-area"></i>
                        @Html.ActionLink(@User.Identity.GetUserName(), "ResetPassword", "Account", null, new { @class = "header-area my-account-link" })

                        <div class="logout-panel">
                            @Html.ActionLink("Log out", "Logout", "Account", new { returnUrl = @Request.Url.AbsoluteUri }, null)
                        </div>
                    </div>
                }
                else
                {
                    <div class="user-area">
                        <div class="logout-panel">
                            @Html.ActionLink("Log in", "Login", "Account")
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="container  @ViewBag.ContainerClass">
        <div class="main-site-heading">
            <div class="title">@Html.ActionLink("Budget - Receipts and Expenditure Management", "Index", "Home", null, new { @class = "navbar-brand" })</div>
            <div class="logo"></div>

        </div>
        <div class="clearboth"></div>
        <div class="body-container body-content">
            @if (Request.IsAuthenticated)
            {
                @Html.Partial("_Menu");

            }
            else
            {
                <div class="menu-bar"><div class="row"></div></div>
            }
            @RenderSection("SiteHeading", false)
            <div class="clearboth"></div>
            @if (IsSectionDefined("Breadcrumb"))
            {
                @RenderSection("Breadcrumb", false)
            }
            else
            {
                <div class="main-breadcrumb">
                    @Html.MvcSiteMap().SiteMapPath()
                </div>
            }
            @RenderBody()
        </div>
        <div class="clearboth"></div>
        <footer>
            <div class="bottombar">
                <div class="footermenu">
                    <span>Copyright @DateTime.Now.Year. All rights reserved, Gov.ie, Budget - Receipts and Expenditure Management</span>
                    @Html.ActionLink("Contact Us", "Index", "ContactUs")
                </div>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/app")
    @RenderSection("scripts", required: false)
</body>
</html>

Code/BudgetWebsite/BudgetWebsite/Views/Shared/_Menu.cshtml
@using Databank.Helpers
@using Microsoft.AspNet.Identity
@using Services.Services
<div class="menu-bar">
    <div class="row">

        <div class="col tab not-selected">
            <a href="@Url.Action("Index", "Home")">Home</a>
        </div>

        @{

            var userId = Convert.ToInt32(HttpContext.Current.User.Identity.GetUserId());
            var accountService = new AccountService();
            var reports = accountService.GetUserReports(userId).ToList();
            var categories = reports.Select(x => x.Category).Distinct();
        }

        <div class="hr-menu col sub-menu-parent not-selected">
            Reports
            <div class="sub-menu">
                @foreach (var category in categories)
                {
                    <ul class="menu-section">
                        <li class="sub-heading">@category</li>

                        @{
                            var catReports = reports.Where(x => x.Category == category).ToList();
                        }

                        @foreach (var report in catReports)
                        {
                            <li class="sub-menu-item">
                                <a href="@report.ReportUrl">@report.ReportName</a>
                            </li>
                        }

                    </ul>
                            }
            </div>
        </div>

        <div class="col tab not-selected">
            <a href="@Url.Action("Index", "FileHistory")">File History</a>
        </div>

        @if (SecurityHelper.IsAdmin())
        {
            <div class="col tab not-selected">
                <a href="@Url.Action("Index", "Admin")">Administration</a>
            </div>
        }
    </div>
</div>

Code/BudgetWebsite/BudgetWebsite/Views/Shared/_ReportMenu.cshtml
@model Databank.Models.ModuleViewModel
@using System.Configuration
@using Databank.Helpers

@{
    var rootUrl = ConfigurationManager.AppSettings["SiteUrl"];
}

<div class="report-tree">

    @if (Model.ReportMenu.Any(x => x.HrAccessOnly == false))
    {
        foreach (var menuSection in Model.ReportMenu.Where(x => x.HrAccessOnly == false).Select(x => x.Section).Distinct())
        {
            <ul>
                <li><span>@menuSection</span></li>
                @foreach (var menuItem in Model.ReportMenu.Where(x => x.Section == menuSection))
                {
                    var reportUrl = $"{rootUrl}Webforms/ReportViewer.aspx?tab={(int)menuItem.Tab}&module={((int)menuItem.Module)}&item={menuItem.Url}&reportName={menuItem.Title}";
                    var selectedClass = !string.IsNullOrEmpty(Model.SelectedReport) && Model.SelectedReport == menuItem.Url ? "selected-report" : "not-selected-report";

                    <li class="report-link @selectedClass"><a href="@reportUrl">@menuItem.Title</a></li>
                }
            </ul>
        }
    }
    @if (SecurityHelper.LocalHrPermissions(Model.SecuritySource))
    {
        if (Model.ReportMenu.Any(x => x.HrAccessOnly))
        {
            foreach (var menuSection in Model.ReportMenu.Where(x => x.HrAccessOnly).Select(x => x.Section).Distinct())
            {
                <ul>
                    <li><span>@menuSection</span></li>
                    @foreach (var menuItem in Model.ReportMenu.Where(x => x.Section == menuSection))
                    {
                    var reportUrl = $"{rootUrl}Webforms/ReportViewer.aspx?tab={(int)menuItem.Tab}&module={((int)menuItem.Module)}&item={menuItem.Url}&reportName={menuItem.Title}";
                        var selectedClass = !string.IsNullOrEmpty(Model.SelectedReport) && Model.SelectedReport == menuItem.Url ? "selected-report" : "not-selected-report";

                        <li class="report-link @selectedClass"><a href="@reportUrl">@menuItem.Title</a></li>
                    }
                </ul>
            }
        }
    }
</div>